site_name: TESIS@AVALOS
theme: 'cosmo'
extra:
    theme_inverse: true
pages:
    - Introduction: index.md
    - Organization: tesis.md
    - Progreso:
      - 'S 1'  : 'session/w1.md'
      - 'S 2'  : 'session/w2.md'
      - 'S 3'  : 'session/w3.md'
      - 'S 4'  : 'session/w4.md'
      - 'S 5'  : 'session/w5.md'
      - 'S 6'  : 'session/w6.md'
      - 'S 7'  : 'session/w7.md'
    - WorkSetup: WorkSetup.md
    - Sawyer:
      - 'Description': 'sawyer/sawyer.md'
      - 'ROS':  'sawyer/ROS.md'
      - 'Examples': 'sawyer/examples.md'
      - 'Simulator':  'sawyer/simulator.md'
    - Links: links.md
